-- keys/submaps/vim-operators.lua
-- D-MOTION, C-MOTION, Y-MOTION with nested I/A/G sub-submaps

local vim = require("vim") ---@class vim
local motion = vim.motion
local count = vim.count
local reg = vim.registers
local wk = require("whichkey") ---@class WhichKey

local leader = (require("config").keys or {}).leader or "SUPER"
local act = (require("config").keys or {}).activate or "ESCAPE"

local function b(keys, fn, opts)
  hl.bind(keys, fn, opts)
end
local function bd(keys, desc, fn)
  hl.bind(keys, fn, { description = desc })
end
local function send(mods, key, window)
  hl.dispatch(hl.dsp.send_shortcut({ mods = mods, key = key, window = window }))
end
local function submap(n)
  hl.dispatch(hl.dsp.submap(n))
end

local function exit_footer(return_submap)
  b("ESCAPE", function()
    count.clear()
    submap("NORMAL")
  end)
  b("BackSpace", function()
    count.clear()
    submap(return_submap)
  end)
  b(leader .. " + " .. act, function()
    hl.dispatch(hl.dsp.submap("reset"))
  end)
  b("SPACE", function()
    wk.toggle()
  end)
  b("catchall", function()
    submap(return_submap)
  end)
end

-- ---------------------------------------------------------------------------
-- D-MOTION
-- ---------------------------------------------------------------------------
hl.define_submap("D-MOTION", "reset", function()
  -- Word motions
  bd("w", "Next word", function()
    motion.send_raw({ "CTRL SHIFT", "RIGHT" }, count.get())
    reg.handle_delete("CTRL", "x", "NORMAL")
  end)
  b("SHIFT + w", function()
    motion.send_raw({ "CTRL SHIFT", "RIGHT" }, count.get())
    reg.handle_delete("CTRL", "x", "NORMAL")
  end)
  bd("e", "Next end of word", function()
    motion.send_raw({ "CTRL SHIFT", "RIGHT" }, count.get())
    reg.handle_delete("CTRL", "x", "NORMAL")
  end)
  b("SHIFT + e", function()
    motion.send_raw({ "CTRL SHIFT", "RIGHT" }, count.get())
    reg.handle_delete("CTRL", "x", "NORMAL")
  end)
  bd("b", "Prev word", function()
    motion.send_raw({ "CTRL SHIFT", "LEFT" }, count.get())
    reg.handle_delete("CTRL", "x", "NORMAL")
  end)
  b("SHIFT + b", function()
    motion.send_raw({ "CTRL SHIFT", "LEFT" }, count.get())
    reg.handle_delete("CTRL", "x", "NORMAL")
  end)

  -- Line
  bd("d", "Delete line", function()
    motion.send_sequence({ { "", "HOME" }, { "SHIFT", "End" } })
    reg.handle_delete("CTRL", "x", "NORMAL")
    send("", "BackSpace")
    send("", "DOWN")
  end)

  -- To end/start
  bd("SHIFT + 4", "End of line", function()
    count.clear()
    motion.send_raw({ "SHIFT", "End" }, 1)
    reg.handle_delete("CTRL", "x", "NORMAL")
  end)
  bd("SHIFT + 6", "Start of line", function()
    count.clear()
    motion.send_raw({ "SHIFT", "Home" }, 1)
    reg.handle_delete("CTRL", "x", "NORMAL")
  end)
  bd("0", "Start of line", function()
    count.clear()
    motion.send_raw({ "SHIFT", "Home" }, 1)
    reg.handle_delete("CTRL", "x", "NORMAL")
  end)

  -- Delete mark
  bd("m", "+Delete Mark", function()
    count.clear()
    submap("DELETE-MARK")
  end)

  -- Sub-submaps
  bd("i", "+Inner", function()
    count.clear()
    submap("D-I")
  end)
  b("SHIFT + i", function()
    submap("D-I")
  end)
  bd("a", "+Around", function()
    count.clear()
    submap("D-A")
  end)
  b("SHIFT + a", function()
    submap("D-A")
  end)
  bd("g", "+Go", function()
    count.clear()
    submap("D-G")
  end)

  exit_footer("D-MOTION")
end)

hl.define_submap("D-I", "D-MOTION", function()
  bd("w", "Word", function()
    motion.send_sequence({ { "CTRL", "LEFT" }, { "CTRL SHIFT", "RIGHT" } })
    reg.handle_delete("CTRL", "x", "NORMAL")
  end)
  b("SHIFT + w", function()
    motion.send_sequence({ { "CTRL", "LEFT" }, { "CTRL SHIFT", "RIGHT" } })
    reg.handle_delete("CTRL", "x", "NORMAL")
  end)
  bd("p", "Paragraph", function()
    motion.send_sequence({ { "CTRL", "UP" }, { "CTRL SHIFT", "DOWN" } })
    reg.handle_delete("CTRL", "x", "NORMAL")
  end)
  b("SHIFT + p", function()
    motion.send_sequence({ { "CTRL", "UP" }, { "CTRL SHIFT", "DOWN" } })
    reg.handle_delete("CTRL", "x", "NORMAL")
  end)
  bd("SHIFT + g", "Last line", function()
    motion.send_raw({ "CTRL SHIFT", "END" }, 1)
    reg.handle_delete("CTRL", "x", "NORMAL")
  end)
  b("ESCAPE", function()
    submap("NORMAL")
  end)
  b("BackSpace", function()
    submap("D-MOTION")
  end)
  b(leader .. " + " .. act, function()
    hl.dispatch(hl.dsp.submap("reset"))
  end)
  b("SPACE", function()
    wk.toggle()
  end)
  b("catchall", function()
    submap("D-I")
  end)
end)

hl.define_submap("D-A", "D-MOTION", function()
  bd("w", "Word", function()
    motion.send_sequence({ { "CTRL", "LEFT" }, { "CTRL SHIFT", "RIGHT" } })
    reg.handle_delete("CTRL", "x", "NORMAL")
  end)
  b("SHIFT + w", function()
    motion.send_sequence({ { "CTRL", "LEFT" }, { "CTRL SHIFT", "RIGHT" } })
    reg.handle_delete("CTRL", "x", "NORMAL")
  end)
  bd("p", "Paragraph", function()
    motion.send_sequence({ { "CTRL", "UP" }, { "CTRL SHIFT", "DOWN" } })
    reg.handle_delete("CTRL", "x", "NORMAL")
  end)
  b("SHIFT + p", function()
    motion.send_sequence({ { "CTRL", "UP" }, { "CTRL SHIFT", "DOWN" } })
    reg.handle_delete("CTRL", "x", "NORMAL")
  end)
  b("ESCAPE", function()
    submap("NORMAL")
  end)
  b("BackSpace", function()
    submap("D-MOTION")
  end)
  b(leader .. " + " .. act, function()
    hl.dispatch(hl.dsp.submap("reset"))
  end)
  b("SPACE", function()
    wk.toggle()
  end)
  b("catchall", function()
    submap("D-A")
  end)
end)

hl.define_submap("D-G", "D-MOTION", function()
  bd("g", "First line", function()
    motion.send_raw({ "CTRL SHIFT", "HOME" }, 1)
    reg.handle_delete("CTRL", "x", "NORMAL")
  end)
  bd("SHIFT + g", "Last line", function()
    motion.send_raw({ "CTRL SHIFT", "END" }, 1)
    reg.handle_delete("CTRL", "x", "NORMAL")
  end)
  b("ESCAPE", function()
    submap("NORMAL")
  end)
  b("BackSpace", function()
    submap("D-MOTION")
  end)
  b(leader .. " + " .. act, function()
    hl.dispatch(hl.dsp.submap("reset"))
  end)
  b("SPACE", function()
    wk.toggle()
  end)
  b("catchall", function()
    submap("D-G")
  end)
end)

-- ---------------------------------------------------------------------------
-- C-MOTION
-- ---------------------------------------------------------------------------
hl.define_submap("C-MOTION", "reset", function()
  bd("w", "Next word", function()
    motion.send_raw({ "CTRL SHIFT", "RIGHT" }, count.get())
    hl.dispatch(hl.dsp.submap("INSERT"))
  end)
  b("SHIFT + w", function()
    motion.send_sequence({ { "CTRL SHIFT", "RIGHT" }, { "SHIFT", "Left" }, { "", "DELETE" } })
    submap("INSERT")
  end)
  bd("e", "End of next word", function()
    motion.send_sequence({ { "CTRL SHIFT", "RIGHT" }, { "SHIFT", "Left" }, { "", "DELETE" } })
    submap("INSERT")
  end)
  bd("b", "Prev word", function()
    motion.send_raw({ "CTRL SHIFT", "LEFT" }, count.get())
    hl.dispatch(hl.dsp.submap("INSERT"))
  end)
  b("SHIFT + b", function()
    motion.send_sequence({ { "CTRL SHIFT", "LEFT" }, { "", "DELETE" } })
    submap("INSERT")
  end)

  -- Line
  bd("c", "Change line", function()
    motion.send_sequence({ { "", "HOME" }, { "SHIFT", "End" }, { "", "DELETE" } })
    submap("INSERT")
  end)

  -- To end/start
  bd("SHIFT + 4", "End of line", function()
    count.clear()
    motion.send_sequence({ { "SHIFT", "End" }, { "", "DELETE" } })
    submap("INSERT")
  end)
  bd("SHIFT + 6", "Start of line", function()
    count.clear()
    motion.send_sequence({ { "SHIFT", "Home" }, { "", "DELETE" } })
    submap("INSERT")
  end)
  bd("0", "Start of line", function()
    count.clear()
    motion.send_sequence({ { "SHIFT", "Home" }, { "", "DELETE" } })
    submap("INSERT")
  end)
  bd("SHIFT + g", "Last line", function()
    count.clear()
    motion.send_raw({ "CTRL SHIFT", "END" }, 1)
    reg.handle_delete("CTRL", "x", "INSERT")
  end)

  -- Sub-submaps
  bd("i", "+Inner", function()
    count.clear()
    submap("C-I")
  end)
  b("SHIFT + i", function()
    submap("C-I")
  end)
  bd("a", "+Around", function()
    count.clear()
    submap("C-A")
  end)
  b("SHIFT + a", function()
    submap("C-A")
  end)
  bd("g", "+Go", function()
    count.clear()
    submap("C-G")
  end)

  b("ESCAPE", function()
    count.clear()
    submap("NORMAL")
  end)
  b("BackSpace", function()
    count.clear()
    submap("NORMAL")
  end)
  b(leader .. " + " .. act, function()
    hl.dispatch(hl.dsp.submap("reset"))
  end)
  b("SPACE", function()
    wk.toggle()
  end)
  b("catchall", function()
    submap("C-MOTION")
  end)
end)

hl.define_submap("C-I", "C-MOTION", function()
  bd("w", "Word", function()
    motion.send_sequence({ { "CTRL", "LEFT" }, { "CTRL SHIFT", "RIGHT" }, { "", "BackSpace" } })
    submap("INSERT")
  end)
  b("SHIFT + w", function()
    motion.send_sequence({ { "CTRL", "LEFT" }, { "CTRL SHIFT", "RIGHT" }, { "", "BackSpace" } })
    submap("INSERT")
  end)
  bd("p", "Paragraph", function()
    motion.send_sequence({ { "CTRL", "UP" }, { "CTRL SHIFT", "DOWN" } })
    reg.handle_delete("CTRL", "x", "INSERT")
  end)
  b("SHIFT + p", function()
    motion.send_sequence({ { "CTRL", "UP" }, { "CTRL SHIFT", "DOWN" } })
    reg.handle_delete("CTRL", "x", "INSERT")
  end)
  b("ESCAPE", function()
    submap("NORMAL")
  end)
  b("BackSpace", function()
    submap("C-MOTION")
  end)
  b(leader .. " + " .. act, function()
    hl.dispatch(hl.dsp.submap("reset"))
  end)
  b("SPACE", function()
    wk.toggle()
  end)
  b("catchall", function()
    submap("C-I")
  end)
end)

hl.define_submap("C-A", "C-MOTION", function()
  bd("w", "Word", function()
    motion.send_sequence({ { "CTRL", "LEFT" }, { "CTRL SHIFT", "RIGHT" }, { "", "BackSpace" } })
    submap("INSERT")
  end)
  b("SHIFT + w", function()
    motion.send_sequence({ { "CTRL", "LEFT" }, { "CTRL SHIFT", "RIGHT" }, { "", "BackSpace" } })
    submap("INSERT")
  end)
  bd("p", "Paragraph", function()
    motion.send_sequence({ { "CTRL", "UP" }, { "CTRL SHIFT", "DOWN" } })
    reg.handle_delete("CTRL", "x", "INSERT")
  end)
  b("SHIFT + p", function()
    motion.send_sequence({ { "CTRL", "UP" }, { "CTRL SHIFT", "DOWN" } })
    reg.handle_delete("CTRL", "x", "INSERT")
  end)
  b("ESCAPE", function()
    submap("NORMAL")
  end)
  b("BackSpace", function()
    submap("C-MOTION")
  end)
  b(leader .. " + " .. act, function()
    hl.dispatch(hl.dsp.submap("reset"))
  end)
  b("SPACE", function()
    wk.toggle()
  end)
  b("catchall", function()
    submap("C-A")
  end)
end)

hl.define_submap("C-G", "C-MOTION", function()
  bd("g", "First line", function()
    motion.send_raw({ "CTRL SHIFT", "HOME" }, 1)
    reg.handle_delete("CTRL", "x", "INSERT")
  end)
  bd("SHIFT + g", "Last line", function()
    motion.send_raw({ "CTRL SHIFT", "END" }, 1)
    reg.handle_delete("CTRL", "x", "INSERT")
  end)
  b("ESCAPE", function()
    submap("NORMAL")
  end)
  b("BackSpace", function()
    submap("C-MOTION")
  end)
  b(leader .. " + " .. act, function()
    hl.dispatch(hl.dsp.submap("reset"))
  end)
  b("SPACE", function()
    wk.toggle()
  end)
  b("catchall", function()
    submap("C-G")
  end)
end)

-- ---------------------------------------------------------------------------
-- Y-MOTION
-- ---------------------------------------------------------------------------
hl.define_submap("Y-MOTION", "reset", function()
  bd("w", "Next word", function()
    motion.send_raw({ "CTRL SHIFT", "RIGHT" }, count.get())
    reg.handle_yank("CTRL", "c", "NORMAL")
  end)
  bd("e", "Next end of word", function()
    motion.send_raw({ "CTRL SHIFT", "RIGHT" }, count.get())
    reg.handle_yank("CTRL", "c", "NORMAL")
  end)
  bd("b", "Prev word", function()
    motion.send_raw({ "CTRL SHIFT", "LEFT" }, count.get())
    reg.handle_yank("CTRL", "c", "NORMAL")
  end)
  b("SHIFT + w", function()
    motion.send_raw({ "CTRL SHIFT", "RIGHT" }, count.get())
    reg.handle_yank("CTRL", "c", "NORMAL")
  end)
  b("SHIFT + e", function()
    motion.send_raw({ "CTRL SHIFT", "RIGHT" }, count.get())
    reg.handle_yank("CTRL", "c", "NORMAL")
  end)
  b("SHIFT + b", function()
    motion.send_raw({ "CTRL SHIFT", "LEFT" }, count.get())
    reg.handle_yank("CTRL", "c", "NORMAL")
  end)

  -- Line
  bd("y", "Yank line", function()
    motion.send_sequence({ { "", "HOME" }, { "SHIFT", "End" } })
    reg.handle_yank("CTRL", "c", "NORMAL")
    send("", "DOWN")
  end)

  -- To end/start
  bd("SHIFT + 4", "End of line", function()
    count.clear()
    motion.send_raw({ "SHIFT", "End" }, 1)
    reg.handle_yank("CTRL", "c", "NORMAL")
  end)
  bd("0", "Start of line", function()
    count.clear()
    motion.send_raw({ "SHIFT", "Home" }, 1)
    reg.handle_yank("CTRL", "c", "NORMAL")
  end)
  bd("SHIFT + 6", "End of line", function()
    count.clear()
    motion.send_raw({ "SHIFT", "Home" }, 1)
    reg.handle_yank("CTRL", "c", "NORMAL")
  end)
  bd("SHIFT + g", "Last line", function()
    motion.send_raw({ "CTRL SHIFT", "END" }, 1)
    reg.handle_yank("CTRL", "c", "NORMAL")
  end)

  -- Sub-submaps
  bd("i", "+Inner", function()
    count.clear()
    submap("Y-I")
  end)
  b("SHIFT + i", function()
    submap("Y-I")
  end)
  bd("a", "+Around", function()
    count.clear()
    submap("Y-A")
  end)
  b("SHIFT + a", function()
    submap("Y-A")
  end)
  bd("g", "+Go", function()
    count.clear()
    submap("Y-G")
  end)

  b("ESCAPE", function()
    count.clear()
    submap("NORMAL")
  end)
  b(leader .. " + " .. act, function()
    hl.dispatch(hl.dsp.submap("reset"))
  end)
  b("SPACE", function()
    wk.toggle()
  end)
  b("catchall", function()
    submap("Y-MOTION")
  end)
end)

hl.define_submap("Y-I", "Y-MOTION", function()
  bd("w", "Word", function()
    motion.send_sequence({ { "CTRL", "LEFT" }, { "CTRL SHIFT", "RIGHT" } })
    reg.handle_yank("CTRL", "c", "NORMAL")
  end)
  b("SHIFT + w", function()
    motion.send_sequence({ { "CTRL", "LEFT" }, { "CTRL SHIFT", "RIGHT" } })
    reg.handle_yank("CTRL", "c", "NORMAL")
  end)
  bd("p", "Paragraph", function()
    motion.send_sequence({ { "CTRL", "UP" }, { "CTRL SHIFT", "DOWN" } })
    reg.handle_yank("CTRL", "c", "NORMAL")
  end)
  b("SHIFT + p", function()
    motion.send_sequence({ { "CTRL", "UP" }, { "CTRL SHIFT", "DOWN" } })
    reg.handle_yank("CTRL", "c", "NORMAL")
  end)
  b("ESCAPE", function()
    submap("NORMAL")
  end)
  b("BackSpace", function()
    submap("Y-MOTION")
  end)
  b(leader .. " + " .. act, function()
    hl.dispatch(hl.dsp.submap("reset"))
  end)
  b("SPACE", function()
    wk.toggle()
  end)
  b("catchall", function()
    submap("Y-I")
  end)
end)

hl.define_submap("Y-A", "Y-MOTION", function()
  bd("w", "Word", function()
    motion.send_sequence({ { "CTRL", "LEFT" }, { "CTRL SHIFT", "RIGHT" } })
    reg.handle_yank("CTRL", "c", "NORMAL")
  end)
  b("SHIFT + w", function()
    motion.send_sequence({ { "CTRL", "LEFT" }, { "CTRL SHIFT", "RIGHT" } })
    reg.handle_yank("CTRL", "c", "NORMAL")
  end)
  bd("p", "Paragraph", function()
    motion.send_sequence({ { "CTRL", "UP" }, { "CTRL SHIFT", "DOWN" } })
    reg.handle_yank("CTRL", "c", "NORMAL")
  end)
  b("SHIFT + p", function()
    motion.send_sequence({ { "CTRL", "UP" }, { "CTRL SHIFT", "DOWN" } })
    reg.handle_yank("CTRL", "c", "NORMAL")
  end)
  b("ESCAPE", function()
    submap("NORMAL")
  end)
  b("BackSpace", function()
    submap("Y-MOTION")
  end)
  b(leader .. " + " .. act, function()
    hl.dispatch(hl.dsp.submap("reset"))
  end)
  b("SPACE", function()
    wk.toggle()
  end)
  b("catchall", function()
    submap("Y-A")
  end)
end)

hl.define_submap("Y-G", "Y-MOTION", function()
  bd("g", "First line", function()
    motion.send_raw({ "CTRL SHIFT", "HOME" }, 1)
    reg.handle_yank("CTRL", "c", "NORMAL")
  end)
  bd("SHIFT + g", "Last line", function()
    motion.send_raw({ "CTRL SHIFT", "END" }, 1)
    reg.handle_yank("CTRL", "c", "NORMAL")
  end)
  b("ESCAPE", function()
    submap("NORMAL")
  end)
  b("BackSpace", function()
    submap("Y-MOTION")
  end)
  b(leader .. " + " .. act, function()
    hl.dispatch(hl.dsp.submap("reset"))
  end)
  b("SPACE", function()
    wk.toggle()
  end)
  b("catchall", function()
    submap("Y-G")
  end)
end)
